### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by Shmarkus** [swagger-api/swagger-form-editor#5]
Running "npm i" fails:
```
$ npm i

> gifsicle@0.1.7 postinstall C:\Users\Marku\Projects\swagger-form-editor\node_modules\gifsicle
> node index.js

path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.basename (path.js:833:5)
    at C:\Users\Marku\Projects\swagger-form-editor\node_modules\download\index.js:35:43
    at each (C:\Users\Marku\Projects\swagger-form-editor\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\Users\Marku\Projects\swagger-form-editor\node_modules\download\index.js:33:5)
    at C:\Users\Marku\Projects\swagger-form-editor\node_modules\bin-wrapper\index.js:108:20
    at C:\Users\Marku\Projects\swagger-form-editor\node_modules\bin-wrapper\index.js:141:24
    at C:\Users\Marku\Projects\swagger-form-editor\node_modules\bin-check\index.js:30:20
    at C:\Users\Marku\Projects\swagger-form-editor\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:166:21)
npm WARN swaggereditor@0.0.0 No repository field.
npm WARN swaggereditor@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marku\AppData\Roaming\npm-cache\_logs\2018-05-16T19_13_32_098Z-debug.log
```
[2018-05-16T19_13_32_098Z-debug.log](https://github.com/swagger-api/swagger-form-editor/files/2010506/2018-05-16T19_13_32_098Z-debug.log)

NPM version: 5.5.1

**Comment by andrelec1** [comment]
same here
